<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Singularity</string>
	</array>
	<key>name</key>
	<string>Singularity Definition File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.singularity</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.singularity</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.singularity</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^(\s*)((#).*$\n?)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.enum.tag-digest</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Header</string>
			<key>match</key>
			<string>^((Bootstrap|From|Stage|OSVersion|MirrorURL|Include|Library):)\s*(.+)</string>
			<key>name</key>
			<string>keyword.control.singularity.header</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Section (other)</string>
			<key>match</key>
			<string>^%(files|labels|help)\s*</string>
			<key>name</key>
			<string>keyword.control.singularity.section_other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^%(environment|post|runscript|setup|startscript|test)\s*</string>
			<key>comment</key>
			<string>Section (shell)</string>
			<key>end</key>
			<string>^(?=%[a-z]+)</string>
			<key>name</key>
			<string>keyword.control.singularity.section_shell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.singularity-container</string>
	<key>uuid</key>
	<string>1e6e5d38-e76a-11e9-888d-3c15c2c2816c</string>
</dict>
</plist>
